azs:
- name: z1
  cloud_properties:
    zone: europe-west1-b
- name: z2
  cloud_properties:
    zone: europe-west1-c
- name: z3
  cloud_properties:
    zone: europe-west1-d

networks:
- name: default
  type: manual
  subnets:
  - range: 10.0.0.0/24
    gateway: 10.0.0.1
    reserved: [10.0.0.2-10.0.0.9]
    static: [10.0.0.10-10.0.0.19]
    azs:
    - z1
    - z2
    - z3
    dns:
    - 8.8.8.8
    - 8.8.4.4
    cloud_properties:
      ephemeral_external_ip: false
      network_name: bosh
      subnetwork_name: bosh-europe-west1
      tags:
      - internal
      - no-ip

compilation:
  workers: 1
  network: default
  az: z1
  vm_type: compilation
  reuse_compilation_vms: true

vm_types:
- name: f1-micro
  cloud_properties:
    machine_type: f1-micro
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
    service_scopes:
    - compute.readonly
    - devstorage.read_write

- name: compilation
  cloud_properties:
    machine_type: n1-highcpu-4
    root_disk_size_gb: 50
    root_disk_type: pd-ssd
    service_scopes:
    - compute.readonly
    - devstorage.read_write
    preemptible: true

disk_pools:
  - name: 100GB
    disk_size: 100000
    cloud_properties:
      type: pd-standard
